trigger:
  batch: false
  branches:
    include:
      - dev
  paths:
   include:
    - src/Services/Basket/*

pr:
  branches:
    include:
      - dev
  paths:
   include:
    - src/Services/Basket/*

variables:
  - name: imageName
    value: 'eshop/basket.api:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI
  

resources:
- repo: self

jobs:
- job: Phase_1
  displayName: eShopOnContainers build

  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: Docker@1
    displayName: 'Build the Basket API docker image'
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/basket.api:$(Build.BuildNumber)'
      dockerFile: 'src/Services/Basket/Basket.API/Dockerfile'
      useDefaultContext: false
      buildContext: .
      
  - script: |
      export id=$(docker images --filter "label=test=true" -q | head -1)
      docker create --name testcontainer $id
      docker cp testcontainer:/TestResults ./TestResults
      docker rm testcontainer
    displayName: 'get test results'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/test*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/TestResults'
      publishRunAttachments: true
    displayName: 'Publish test results'

  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      command: login

  - task: Bash@3
    inouts:
      displayName: 'Whitesource Setup'
      targetType: inline
      script: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar 

  - task: Bash@3
    inputs:
      displayName: 'Whitesource Run'
      targetType: inline
      script: java -jar wss-unified-agent.jar -noConfig true -apiKey $WHITESOURCE_API -wss.url https://app.whitesourcesoftware.com/agent -product eShopOnContainers -project basket.api

  - task: Docker@1
    displayName: 'Push the basket api image to the ACR'
    inputs:
      command: 'push'
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/basket.api:$(Build.BuildNumber)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: helm'
    inputs:
      PathtoPublish: k8s/helm/basket-api
      ArtifactName: helm

- job: Phase_2
  displayName: CredScan

  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
      scanFolder: 'src/Services/Basket'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
    displayName: 'Publish Security Analysis Logs'


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
    displayName: 'Create Security Analysis Report'
    inputs:
      CredScan: true


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true

    continueOnError: true


