
trigger:
  batch: true
  branches:
  include:
    - dev
  paths:
   include:
    - src/web/WebSPA

variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

resources:
- repo: self
phases:
- phase: Phase_1
  displayName: eShopOnContainers build

  condition: succeeded()
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - task: Docker@1
    displayName: 'Build the WebSPA docker image'
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/webspa:$(Build.BuildId)'
      dockerFile: 'src/Web/WebSPA/DockerFile'

  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      command: login

  - task: Docker@1
    displayName: 'Push the WebSPA image to the ACR'
    inputs:
      command: 'push'
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/webspa:$(Build.BuildId)'

- phase: Phase_2
  displayName: CredScan

  condition: succeeded()
  queue:
    name: Hosted VS2017
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
    displayName: 'Publish Security Analysis Logs'


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
    displayName: 'Create Security Analysis Report'
    inputs:
      CredScan: true


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true

    continueOnError: true


