trigger:
  batch: false
  branches:
    include:
      - dev
  paths:
   include:
    - src/Web/WebMVC/*

pr:
  branches:
    include:
      - dev
  paths:
   include:
    - src/Web/WebMVC/*

variables:
  imageName: 'eshop/webmvc:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

resources:
- repo: self

jobs:
- job: Phase_1
  displayName: eShopOnContainers build

  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: Docker@1
    displayName: 'Build the WebMVC docker image'
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/webMVC:$(Build.BuildNumber)'
      dockerFile: 'src/Web/WebMVC/Dockerfile'
      useDefaultContext: false
      buildContext: .

  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      command: login

  - task: Docker@1
    displayName: 'Push the WebMVC image to the ACR'
    inputs:
      command: 'push'
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/webmvc:$(Build.BuildNumber)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: helm'
    inputs:
      PathtoPublish: k8s/helm/webmvc
      ArtifactName: helm



- job: Phase_2
  displayName: CredScan

  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
      scanFolder: 'src/Web/WebMVC/*'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
    displayName: 'Publish Security Analysis Logs'


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
    displayName: 'Create Security Analysis Report'
    inputs:
      CredScan: true


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true

    continueOnError: true


