trigger:
  batch: false
  branches:
    include:
      - dev
  paths:
   include:
    - src/Services/Marketing/*

pr:
  branches:
    include:
      - dev
  paths:
   include:
    - src/Services/Marketing/*

variables:
  imageName: 'eshop/marketing.api:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

resources:
- repo: self

jobs:
- job: Phase_1
  displayName: eShopOnContainers build

  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: Docker@1
    displayName: 'Build the Marketing API docker image'
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/marketing.api:$(Build.BuildNumber)'
      dockerFile: 'src/Services/Marketing/Marketing.API/Dockerfile'
      useDefaultContext: false
      buildContext: .

  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      command: login

  - task: Bash@3
    inputs:
      displayName: 'Whitesource Setup'
      targetType: inline
      script: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar 

  - task: Bash@3
    inputs:
      displayName: 'Whitesource Run'
      targetType: inline
      script: java -jar wss-unified-agent.jar -noConfig true -apiKey $(whitesource.api) -wss.url https://app.whitesourcesoftware.com/agent -product eShopOnContainers -project marketing.api

  - task: Docker@1
    displayName: 'Push the basket api image to the ACR'
    inputs:
      command: 'push'
      azureSubscriptionEndpoint: 'niyuen (6f3097c6-c15a-44e4-89ba-990aa1a690ec)'
      azureContainerRegistry: niyuen.azurecr.io
      imageName: 'niyuen.azurecr.io/eshop/marketing.api:$(Build.BuildNumber)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: helm'
    inputs:
      PathtoPublish: k8s/helm/marketing-api
      ArtifactName: helm



- job: Phase_2
  displayName: CredScan

  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
      scanFolder: 'src/Services/Marketing'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
    displayName: 'Publish Security Analysis Logs'


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
    displayName: 'Create Security Analysis Report'
    inputs:
      CredScan: true


  - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
    displayName: 'Post Analysis'
    inputs:
      CredScan: true

    continueOnError: true


